package SoftwareIIProject;

import java.time.LocalDateTime;

/**
 * Class creates Appointments Objects
 */
public class Appointments {

    private int appointmentID;
    private String title;
    private String description;
    private String location;
    private String type;
    private LocalDateTime start;
    private LocalDateTime end;
    private LocalDateTime createDate;
    private String createBy;
    private LocalDateTime lastUpdate;
    private String lastUpdateBy;
    private int customerID;
    private int userID;
    private int contactID;
    private String contactName;
    private String customerName;

    /**
     * @param appointmentID     Appointment ID (AutoGenerated)
     * @param title             Title (User input)
     * @param description       Description (User input)
     * @param location          Location (User input)
     * @param type              Type (User input)
     * @param start             Start (ComboBox selection)
     * @param end               End (ComboBox selection)
     * @param createDate        Create Date (User's current time)
     * @param createBy          Create By (User logged in)
     * @param lastUpdate        Last Update (Time when object was created)
     * @param lastUpdateBy      Last Update by (User when object was created)
     * @param customerID        Customer ID (User ComboBox selection)
     * @param userID            User ID (User when object was created or modified)
     * @param contactID         Contact ID (User ComboBox selection)
     * @param contactName       Contact Name (User ComboBox selection)
     * @param customerName      Customer Name (User ComboBox selection)
     */
    public Appointments(int appointmentID, String title, String description, String location, String type, LocalDateTime start, LocalDateTime end, LocalDateTime createDate,
                        String createBy, LocalDateTime lastUpdate, String lastUpdateBy, int customerID, int userID, int contactID, String contactName, String customerName )
    {
        this.appointmentID = appointmentID;
        this.title = title;
        this.description = description;
        this.location = location;
        this.type = type;
        this.start = start;
        this.end = end;
        this.createDate = createDate;
        this.createBy = createBy;
        this.lastUpdate = lastUpdate;
        this.lastUpdateBy = lastUpdateBy;
        this.customerID = customerID;
        this.userID = userID;
        this.contactID = contactID;
        this.contactName = contactName;
        this.customerName = customerName;
    }

    /**
     * @return Appointment ID
     */
    public int getAppointmentID() { return appointmentID; }

    /**
     * @param appointmentID Set Appointment ID
     */
    public void setAppointmentID(int appointmentID) { this.appointmentID = appointmentID; }

    /**
     * @return Title
     */
    public String getTitle() { return title; }

    /**
     * @param title Set Title
     */
    public void setTitle(String title) { this.title = title; }

    /**
     * @return Description
     */
    public String getDescription() { return description; }

    /**
     * @param description Set Description
     */
    public void setDescription(String description) { this.description = description; }

    /**
     * @return Location
     */
    public String getLocation() { return location; }

    /**
     * @param location Set Location
     */
    public void setLocation(String location) { this.location = location; }

    /**
     * @return Type
     */
    public String getType() { return type; }

    /**
     * @param type Set Type
     */
    public void setType(String type) { this.type = type; }

    /**
     * @return Start
     */
    public LocalDateTime getStart() { return start; }

    /**
     * @param start Set Start
     */
    public void setStart(LocalDateTime start) { this.start = start; }

    /**
     * @return End
     */
    public LocalDateTime getEnd() { return end; }

    /**
     * @param end Set End
     */
    public void setEnd(LocalDateTime end) { this.end = end; }

    /**
     * @return Create Date
     */
    public LocalDateTime getCreateDate() { return createDate; }

    /**
     * @param createDate Set Create Date
     */
    public void setCreateDate(LocalDateTime createDate) { this.createDate = createDate; }

    /**
     * @return Create By
     */
    public String getCreateBy() { return createBy; }

    /**
     * @param createBy Set Create By
     */
    public void setCreateBy(String createBy) { this.createBy = createBy; }

    /**
     * @return Last Update
     */
    public LocalDateTime getLastUpdate() { return lastUpdate; }

    /**
     * @param lastUpdate set Last Update
     */
    public void setLastUpdate(LocalDateTime lastUpdate) { this.lastUpdate = lastUpdate; }

    /**
     * @return Last Update By
     */
    public String getLastUpdateBy() { return lastUpdateBy; }

    /**
     * @param lastUpdateBy Set Last Update By
     */
    public void setLastUpdateBy(String lastUpdateBy) { this.lastUpdateBy = lastUpdateBy; }

    /**
     * @return CustomerID
     */
    public int getCustomerID() { return customerID; }

    /**
     * @param customerID Set CustomerID
     */
    public void setCustomerID(int customerID) { this.customerID = customerID; }

    /**
     * @return User ID
     */
    public int getUserID() { return userID; }

    /**
     * @param userID Set User ID
     */
    public void setUserID(int userID) { this.userID = userID; }

    /**
     * @return Contact ID
     */
    public int getContactID() { return contactID; }

    /**
     * @param contactID Set Contact ID
     */
    public void setContactID(int contactID) { this.contactID = contactID; }

    /**
     * @return Contact Name
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * @param contactName Contact Name
     */
    public void setContactName(String contactName) { this.contactName = contactName; }

    /**
     * @return Customer Name
     */
    public String getCustomerName() { return customerName; }

    /**
     * @param customerName set CustomerName
     */
    public void setCustomerName(String customerName) { this.customerName = customerName; }




}
