package SoftwareIIProject;

import java.sql.Date;

/**
 * Class builds Customer Objects
 */
public class Customer {

    private int id;
    private String name;
    private String address;
    private String postalCode;
    private String phone;
    private Date createDate;
    private String createBy;
    private Date lastUpdated;
    private String lastUpdatedBy;
    private String division;
    private String country;

    /**
     * @param id            Customer ID (AutoGenerated)
     * @param name          Name (User Input)
     * @param address       Address(User Input)
     * @param postalCode    Postal Code (User Input)
     * @param phone         Phone (User Input)
     * @param createDate    Create Date (User's date)
     * @param createBy      Create By (User)
     * @param lastUpdated   Last Updated (Most recent Date)
     * @param lastUpdatedBy Last Updated By (Most recent user)
     * @param division      Division (Division ComboBox)
     * @param country       Country (Country ComboBox)
     */
    public Customer(int id, String name, String address, String postalCode, String phone, Date createDate, String createBy,
                    Date lastUpdated, String lastUpdatedBy, String division, String country)
    {
        this.id = id;
        this.name = name;
        this.address = address;
        this.postalCode = postalCode;
        this.phone = phone;
        this.createDate = createDate;
        this.createBy = createBy;
        this.lastUpdated = lastUpdated;
        this.lastUpdatedBy = lastUpdatedBy;
        this.division = division;
        this.country = country;
    }

    /**
     * @return Customer ID
     */
    public  int getId(){return id;}

    /**
     * @param id Set Customer ID
     */
    public void setId(int id){ this.id = id;}

    /**
     * @return Name
     */
    public String getName(){return name;}

    /**
     * @param name Set Name
     */
    public void setName(String name){this.name = name;}

    /**
     * @return Address
     */
    public String getAddress() {return address;}

    /**
     * @param address Set Address
     */
    public void setAddress(String address) {this.address = address;}

    /**
     * @return Postal Code
     */
    public String getPostalCode() {return postalCode;}

    /**
     * @param postalCode Set Postal Code
     */
    public void setPostalCode(String postalCode) {this.postalCode = postalCode;}

    /**
     * @return Phone Number
     */
    public String getPhone() {return phone;}

    /**
     * @param phone Set Phone Number
     */
    public void setPhone(String phone) {this.phone = phone;}

    /**
     * @return Create Date
     */
    public Date getCreateDate() {return createDate;}

    /**
     * @param createDate Set Create Date
     */
    public void setCreateDate(Date createDate) {this.createDate = createDate;}

    /**
     * @return Create By
     */
    public String getCreateBy() {return createBy;}

    /**
     * @param createBy Set Create By
     */
    public void setCreateBy(String createBy) {this.createBy = createBy;}

    /**
     * @return Last Updated
     */
    public Date getLastUpdated() {return lastUpdated;}

    /**
     * @param lastUpdated Set Last Updated
     */
    public void setLastUpdated(Date lastUpdated) {this.lastUpdated = lastUpdated;}

    /**
     * @return Last Updated By
     */
    public String getLastUpdatedBy() {return lastUpdatedBy;}

    /**
     * @param lastUpdatedBy Set Last Update By
     */
    public void setLastUpdatedBy(String lastUpdatedBy) {this.lastUpdatedBy = lastUpdatedBy;}

    /**
     * @return Division
     */
    public String getDivision() {return division;}

    /**
     * @param division Set Division
     */
    public void setDivision(String division) {this.division = division;}

    /**
     * @return Country
     */
    public String getCountry() {return country;}

    /**
     * Set Country
     */
    public void setCountry(String country) {this.country = country;}

}
